# Generated by Django 4.2.2 on 2024-12-22 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=128, verbose_name='Nama Survei')),
                ('deskripsi', models.TextField(verbose_name='Deskripsi Survei')),
                ('tgl_mulai', models.DateField(verbose_name='Tanggal Mulai')),
                ('tgl_selesai', models.DateField(verbose_name='Tanggal Berakhir')),
                ('state', models.CharField(choices=[('0', 'Belum Aktif'), ('1', 'Berlangsung'), ('2', 'Selesai')], default=0, max_length=1, verbose_name='Status Survei')),
            ],
        ),
        migrations.CreateModel(
            name='SubKegiatanSurvei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kegiatan', models.CharField(max_length=256, verbose_name='Nama Kegiatan Penilaian')),
                ('status', models.CharField(choices=[('0', 'Belum Aktif'), ('1', 'Berlangsung'), ('2', 'Selesai')], default=0, max_length=1, verbose_name='Status Kegiatan')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='master_alokasi_survey', to='master_survey.surveymodel', verbose_name='Survei/Sensus')),
            ],
        ),
    ]
