# Generated by Django 5.0 on 2025-01-23 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subkegiatansurvei',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_alokasi_survey', to='master_survey.surveymodel', verbose_name='Survei/Sensus'),
        ),
    ]
