# Generated by Django 5.0 on 2023-12-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_survey', '0002_alter_surveymodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveymodel',
            name='salary',
            field=models.FloatField(default=0, verbose_name='Honor Mitra'),
            preserve_default=False,
        ),
    ]
