# Generated by Django 5.0 on 2023-12-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_survey', '0003_surveymodel_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveymodel',
            name='salary',
            field=models.FloatField(verbose_name='Nominal Honor'),
        ),
    ]
