# Generated by Django 5.0 on 2024-11-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_survey', '0004_alter_surveymodel_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveymodel',
            name='salary',
        ),
    ]
