# Generated by Django 5.0 on 2024-12-10 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_survey', '0005_remove_surveymodel_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveymodel',
            name='status',
        ),
        migrations.CreateModel(
            name='SubKegiatanSurvei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kegiatan', models.CharField(max_length=256, verbose_name='Nama Kegiatan Penilaian')),
                ('status', models.CharField(choices=[('0', 'Non Aktif'), ('1', 'Berlangsung'), ('2', 'Selesai')], default=0, max_length=1, verbose_name='Status Survei')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='master_alokasi_survey', to='master_survey.surveymodel', verbose_name='Survei/Sensus')),
            ],
        ),
    ]
