# Generated by Django 5.0 on 2024-12-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_survey', '0006_remove_surveymodel_status_subkegiatansurvei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subkegiatansurvei',
            name='status',
            field=models.CharField(choices=[('0', 'Belum Aktif'), ('1', 'Berlangsung'), ('2', 'Selesai')], default=0, max_length=1, verbose_name='Status Survei'),
        ),
    ]
