# Generated by Django 5.0 on 2024-12-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_survey', '0007_alter_subkegiatansurvei_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveymodel',
            name='state',
            field=models.CharField(choices=[('1', 'Berlangsung'), ('2', 'Selesai')], default=0, max_length=1, verbose_name='Status Survei'),
        ),
        migrations.AlterField(
            model_name='subkegiatansurvei',
            name='status',
            field=models.CharField(choices=[('0', 'Belum Aktif'), ('1', 'Berlangsung'), ('2', 'Selesai')], default=0, max_length=1, verbose_name='Status Kegiatan'),
        ),
    ]
