# Generated by Django 5.0 on 2024-12-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_survey', '0008_surveymodel_state_alter_subkegiatansurvei_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveymodel',
            name='state',
            field=models.CharField(choices=[('0', 'Belum Aktif'), ('1', 'Berlangsung'), ('2', 'Selesai')], default=0, max_length=1, verbose_name='Status Survei'),
        ),
    ]
