# Generated by Django 4.2.2 on 2024-12-22 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JabatanPegawaiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=64, verbose_name='Jabatan')),
            ],
        ),
        migrations.CreateModel(
            name='PangkatPegawaiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golongan', models.CharField(max_length=64, verbose_name='Golongan')),
                ('pangkat', models.CharField(max_length=64, verbose_name='Pangkat')),
            ],
        ),
        migrations.CreateModel(
            name='MasterPegawaiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nama')),
                ('nip', models.CharField(max_length=9, unique=True, verbose_name='NIP')),
                ('nip_bps', models.CharField(max_length=18, unique=True, verbose_name='NIP BPS')),
                ('pendidikan', models.CharField(max_length=64, verbose_name='Pendidikan Terakhir')),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='master_pegawai.jabatanpegawaimodel', verbose_name='Jabatan Pegawai')),
                ('pangkat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='master_pegawai.pangkatpegawaimodel', verbose_name='Pangkat/Golongan Pegawai')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user_pegawai', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
        ),
    ]
