# Generated by Django 5.0 on 2024-11-12 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_pegawai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPegawaiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=9, unique=True, verbose_name='NIP')),
                ('nip_bps', models.CharField(max_length=18, unique=True, verbose_name='NIP BPS')),
                ('pendidikan', models.CharField(max_length=64, verbose_name='Pendidikan Terakhir')),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='master_pegawai.jabatanpegawaimodel', verbose_name='Jabatan Pegawai')),
                ('pangkat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='master_pegawai.pangkatpegawaimodel', verbose_name='Pangkat/Golongan Pegawai')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
