# Generated by Django 5.0 on 2024-11-12 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_pegawai', '0003_alter_masterpegawaimodel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='masterpegawaimodel',
            name='name',
            field=models.CharField(default='Rifki', max_length=64, verbose_name='Nama'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='masterpegawaimodel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
    ]
