# Generated by Django 5.0 on 2023-12-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HonorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=128, verbose_name='Nama')),
                ('tgl_ref_awal', models.DateField(verbose_name='Tanggal Referensi Awal')),
                ('tgl_ref_akhir', models.DateField(verbose_name='Tanggal Referensi Akhir')),
                ('honor_maks', models.FloatField(verbose_name='Nominal Batasan Honor Mitra')),
                ('status', models.CharField(choices=[('0', 'Aktif'), ('1', 'Non Aktif')], default=0, max_length=1, verbose_name='Status Aktif')),
            ],
        ),
    ]
