# Generated by Django 4.2.2 on 2024-12-22 04:57

from django.db import migrations, models
import django.db.models.deletion
import master_petugas.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_survey', '0001_initial'),
        ('master_pegawai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Kode Wilayah')),
                ('region', models.CharField(max_length=128, verbose_name='Nama Wilayah')),
            ],
        ),
        migrations.CreateModel(
            name='RoleMitra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=128, verbose_name='Jabatan/Peran')),
            ],
        ),
        migrations.CreateModel(
            name='MasterPetugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_petugas', models.CharField(max_length=12, unique=True, verbose_name='Kode Petugas')),
                ('nama_petugas', models.CharField(max_length=64, verbose_name='Nama Petugas')),
                ('jk', models.CharField(choices=[('0', 'Laki-laki'), ('1', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('nik', models.CharField(max_length=16, unique=True, validators=[master_petugas.validators.int_validators], verbose_name='NIK')),
                ('npwp', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[master_petugas.validators.int_validators], verbose_name='NPWP')),
                ('tgl_lahir', models.DateField(verbose_name='Tanggal Lahir')),
                ('pendidikan', models.CharField(choices=[('0', 'SD/MI Sederajat'), ('1', 'SMP/SLTP Sederajat'), ('2', 'SMA/SLTA Sederajat'), ('3', 'DI-DIII'), ('4', 'DV/S1'), ('5', 'S2'), ('6', 'S3')], max_length=1, verbose_name='Pendidikan Terakhir')),
                ('pekerjaan', models.CharField(max_length=128, verbose_name='Pekerjaan')),
                ('agama', models.CharField(choices=[('0', 'Islam'), ('1', 'Kristen'), ('2', 'Hindu'), ('3', 'Budha')], max_length=1, verbose_name='Agama')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='Email')),
                ('no_telp', models.CharField(blank=True, max_length=13, null=True, validators=[master_petugas.validators.int_validators], verbose_name='No. Telp (Ex: 6285712345678)')),
                ('alamat', models.CharField(max_length=256, verbose_name='Alamat Domisili')),
                ('status', models.CharField(choices=[('0', 'Aktif'), ('1', 'Non Aktif'), ('2', 'Organik'), ('3', 'Blacklist')], max_length=1, verbose_name='Status Mitra')),
                ('bank', models.CharField(blank=True, choices=[('1', 'BRI'), ('2', 'BNI'), ('3', 'BSI'), ('4', 'BCA'), ('5', 'Mandiri'), ('6', 'Bank Sultra')], max_length=1, null=True, verbose_name='Jenis Bank')),
                ('rekening', models.CharField(blank=True, max_length=16, null=True, verbose_name='Nomor Rekening')),
                ('pemilik_rek', models.CharField(blank=True, max_length=64, null=True, verbose_name='Pemilik Rekening')),
                ('adm_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='region_code', to='master_petugas.administrativemodel', verbose_name='Kode Desa')),
            ],
        ),
        migrations.CreateModel(
            name='AlokasiPetugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pegawai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_alokasi_pegawai', to='master_pegawai.masterpegawaimodel', verbose_name='Pegawai')),
                ('petugas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_alokasi_petugas', to='master_petugas.masterpetugas', verbose_name='Kode Petugas')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='master_alokasi_role', to='master_petugas.rolemitra', verbose_name='Jabatan Petugas')),
                ('sub_kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subkegiatan_survei', to='master_survey.subkegiatansurvei', verbose_name='Kegiatan Survei')),
            ],
        ),
        migrations.CreateModel(
            name='AlokasiPenugasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendata', models.ManyToManyField(to='master_petugas.alokasipetugas')),
                ('pengawas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alokasi_penugasan', to='master_petugas.alokasipetugas', verbose_name='Pengawas')),
            ],
        ),
    ]
