# Generated by Django 5.0 on 2025-01-23 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_pegawai', '0001_initial'),
        ('master_petugas', '0002_alter_masterpetugas_no_telp_alter_masterpetugas_npwp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alokasipetugas',
            name='pegawai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_alokasi_pegawai', to='master_pegawai.masterpegawaimodel', verbose_name='Pegawai (Organik)'),
        ),
        migrations.AlterField(
            model_name='alokasipetugas',
            name='petugas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_alokasi_petugas', to='master_petugas.masterpetugas', verbose_name='Petugas (Mitra)'),
        ),
    ]
