# Generated by Django 5.0 on 2023-12-08 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_honor', '0001_initial'),
        ('master_petugas', '0004_alter_masterpetugas_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alokasipetugas',
            name='const_salary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='master_honor', to='master_honor.honormodel', verbose_name='Batasan Honor Mitra'),
            preserve_default=False,
        ),
    ]
