# Generated by Django 5.0 on 2024-10-01 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_petugas', '0005_alokasipetugas_const_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alokasipetugas',
            name='petugas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_alokasi_petugas', to='master_petugas.masterpetugas', verbose_name='Kode Petugas'),
        ),
    ]
