# Generated by Django 5.0 on 2024-10-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_petugas', '0006_alter_alokasipetugas_petugas'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterpetugas',
            name='jk',
            field=models.CharField(choices=[('0', 'Laki-laki'), ('1', 'Perempuan')], default='1', max_length=1, verbose_name='Jenis Kelamin'),
            preserve_default=False,
        ),
    ]
