# Generated by Django 5.0 on 2024-10-01 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_petugas', '0007_masterpetugas_jk'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Kode Wilayah')),
                ('region', models.CharField(max_length=128, verbose_name='Nama Wilayah')),
            ],
        ),
        migrations.AlterField(
            model_name='masterpetugas',
            name='kode_petugas',
            field=models.CharField(max_length=12, unique=True, verbose_name='Kode Petugas/ID Sobat'),
        ),
        migrations.AddField(
            model_name='masterpetugas',
            name='adm_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='region_code', to='master_petugas.administrativemodel', verbose_name='Asal Wilayah'),
        ),
    ]
