# Generated by Django 5.0 on 2024-10-01 08:11

import django.db.models.deletion
import master_petugas.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_petugas', '0008_administrativemodel_alter_masterpetugas_kode_petugas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterpetugas',
            name='adm_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='region_code', to='master_petugas.administrativemodel', verbose_name='Asal Wilayah'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='masterpetugas',
            name='no_telp',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[master_petugas.validators.int_validators], verbose_name='No. Telp'),
        ),
        migrations.AlterField(
            model_name='masterpetugas',
            name='npwp',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[master_petugas.validators.int_validators], verbose_name='NPWP'),
        ),
    ]
