# Generated by Django 5.0 on 2024-10-02 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_petugas', '0009_alter_masterpetugas_adm_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterpetugas',
            name='bank',
            field=models.CharField(blank=True, choices=[('1', 'BRI'), ('2', 'BNI'), ('3', 'BSI'), ('4', 'BCA'), ('5', 'Mandiri'), ('6', 'Bank Sultra')], max_length=1, null=True, verbose_name='Jenis Bank'),
        ),
        migrations.AddField(
            model_name='masterpetugas',
            name='pemilik_rek',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Pemilik Rekening'),
        ),
        migrations.AddField(
            model_name='masterpetugas',
            name='rekening',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Nomor Rekening'),
        ),
        migrations.AlterField(
            model_name='masterpetugas',
            name='adm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='region_code', to='master_petugas.administrativemodel', verbose_name='Kode Desa'),
        ),
    ]
