# Generated by Django 5.0 on 2024-11-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_petugas', '0011_alter_masterpetugas_kode_petugas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alokasipetugas',
            name='const_salary',
        ),
    ]
