# Generated by Django 5.0 on 2024-11-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_petugas', '0012_remove_alokasipetugas_const_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='alokasipetugas',
            name='honorPerolehan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Jumlah Honor Perolehan'),
        ),
    ]
