# Generated by Django 5.0 on 2024-11-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_petugas', '0013_alokasipetugas_honorperolehan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alokasipetugas',
            name='honorPerolehan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Jumlah Honor Perolehan'),
        ),
    ]
