# Generated by Django 4.2.2 on 2024-11-12 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_petugas', '0014_alter_alokasipetugas_honorperolehan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlokasiPenugasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendata', models.ManyToManyField(to='master_petugas.alokasipetugas')),
                ('pengawas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alokasi_penugasan', to='master_petugas.alokasipetugas', verbose_name='Pengawas')),
            ],
        ),
    ]
