# Generated by Django 4.2.2 on 2024-11-29 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_pegawai', '0005_alter_masterpegawaimodel_user'),
        ('master_petugas', '0015_alokasipenugasan'),
    ]

    operations = [
        migrations.AddField(
            model_name='alokasipetugas',
            name='organik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_alokasi_organik', to='master_pegawai.masterpegawaimodel', verbose_name='Pegawai'),
        ),
        migrations.AlterField(
            model_name='alokasipetugas',
            name='petugas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_alokasi_petugas', to='master_petugas.masterpetugas', verbose_name='Kode Petugas'),
        ),
    ]
