# Generated by Django 5.0 on 2024-12-10 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_penilaian', '0016_alter_kegiatanpenilaianmodel_kegiatan_survey'),
        ('master_petugas', '0019_remove_alokasipetugas_honorperolehan_and_more'),
        ('master_survey', '0006_remove_surveymodel_status_subkegiatansurvei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alokasipetugas',
            name='sub_kegiatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='subkegiatan_survei', to='master_survey.subkegiatansurvei', verbose_name='Kegiatan Survei'),
        ),
        migrations.DeleteModel(
            name='SubKegiatanSurvei',
        ),
    ]
