# Generated by Django 4.2.2 on 2024-12-22 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_penilaian', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterpenilaianpetugas',
            name='penilaian',
        ),
        migrations.AddField(
            model_name='masternilaipetugas',
            name='indikator_penilaian',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='indikator_kegiatan_penilaian', to='master_penilaian.indikatorkegiatanpenilaian'),
            preserve_default=False,
        ),
    ]
