# Generated by Django 5.0 on 2024-10-01 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_penilaian', '0003_kegiatanpenilaianmodel_role_permitted'),
        ('master_petugas', '0006_alter_alokasipetugas_petugas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masternilaipetugas',
            name='petugas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_petugas', to='master_petugas.alokasipetugas'),
        ),
    ]
