# Generated by Django 4.2.2 on 2024-11-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_penilaian', '0004_alter_masternilaipetugas_petugas'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatanpenilaianmodel',
            name='n_max',
            field=models.IntegerField(default=1, verbose_name='Batas Maksimal Penilaian'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kegiatanpenilaianmodel',
            name='n_min',
            field=models.IntegerField(default=1, verbose_name='Batas Minimum Penilaian'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kegiatanpenilaianmodel',
            name='scale',
            field=models.CharField(choices=[('0', 'Ordinal'), ('1', 'Numerik')], default=0, max_length=1, verbose_name='Skala Penilaian'),
        ),
        migrations.AlterField(
            model_name='kegiatanpenilaianmodel',
            name='status',
            field=models.CharField(choices=[('0', 'Aktif'), ('1', 'Selesai'), ('2', 'Tidak Aktif')], default=0, max_length=1, verbose_name='Status Penilaian'),
        ),
    ]
