# Generated by Django 4.2.2 on 2024-11-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_penilaian', '0005_kegiatanpenilaianmodel_n_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kegiatanpenilaianmodel',
            name='n_max',
        ),
        migrations.RemoveField(
            model_name='kegiatanpenilaianmodel',
            name='n_min',
        ),
        migrations.RemoveField(
            model_name='kegiatanpenilaianmodel',
            name='scale',
        ),
        migrations.AddField(
            model_name='indikatorkegiatanpenilaian',
            name='n_max',
            field=models.IntegerField(default=5, verbose_name='Batas Maksimal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indikatorkegiatanpenilaian',
            name='n_min',
            field=models.IntegerField(default=1, verbose_name='Batas Minimum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indikatorkegiatanpenilaian',
            name='scale',
            field=models.CharField(choices=[('0', 'Ordinal'), ('1', 'Numerik')], default=0, max_length=1, verbose_name='Skala Penilaian'),
        ),
    ]
