# Generated by Django 5.0 on 2024-11-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_penilaian', '0006_remove_kegiatanpenilaianmodel_n_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indikatorkegiatanpenilaian',
            name='n_max',
            field=models.IntegerField(default=5, verbose_name='Batas Maksimal'),
        ),
        migrations.AlterField(
            model_name='indikatorkegiatanpenilaian',
            name='n_min',
            field=models.IntegerField(default=1, verbose_name='Batas Minimum'),
        ),
    ]
