# Generated by Django 5.0 on 2024-11-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_penilaian', '0007_alter_indikatorkegiatanpenilaian_n_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatanpenilaianmodel',
            name='token',
            field=models.CharField(default='asdasd', max_length=6, verbose_name='Token Penilaian'),
            preserve_default=False,
        ),
    ]
