# Generated by Django 5.0 on 2024-11-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_penilaian', '0008_kegiatanpenilaianmodel_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kegiatanpenilaianmodel',
            name='token',
        ),
    ]
