# Generated by Django 4.2.2 on 2024-11-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_pegawai', '0005_alter_masterpegawaimodel_user'),
        ('master_penilaian', '0009_remove_kegiatanpenilaianmodel_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='masternilaipetugas',
            name='penilai',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='penilai', to='master_pegawai.masterpegawaimodel'),
            preserve_default=False,
        ),
    ]
