# Generated by Django 4.2.2 on 2024-11-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_penilaian', '0010_masternilaipetugas_penilai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatanpenilaianmodel',
            name='status',
            field=models.CharField(choices=[('0', 'Berlangsung'), ('1', 'Selesai'), ('2', 'Tidak Aktif')], default=0, max_length=1, verbose_name='Status Penilaian'),
        ),
    ]
