# Generated by Django 5.0 on 2024-12-06 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_penilaian', '0012_alter_kegiatanpenilaianmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indikatorkegiatanpenilaian',
            name='kegiatan_penilaian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kegiatan_penilaian_petugas', to='master_penilaian.kegiatanpenilaianmodel'),
        ),
    ]
