# Generated by Django 5.0 on 2024-12-10 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_penilaian', '0013_alter_indikatorkegiatanpenilaian_kegiatan_penilaian'),
        ('master_petugas', '0018_alokasipetugas_nama_kegiatan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kegiatanpenilaianmodel',
            name='nama_kegiatan',
        ),
        migrations.RemoveField(
            model_name='kegiatanpenilaianmodel',
            name='survey',
        ),
        migrations.AddField(
            model_name='kegiatanpenilaianmodel',
            name='kegiatan_survey',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, related_name='penilaian_survei', to='master_petugas.alokasipetugas', verbose_name='Kegiatan Survei'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kegiatanpenilaianmodel',
            name='role_penilai_permitted',
            field=models.ManyToManyField(related_name='role_permitted_penilai', to='master_petugas.rolemitra', verbose_name='Role Penilai'),
        ),
        migrations.AlterField(
            model_name='kegiatanpenilaianmodel',
            name='role_permitted',
            field=models.ManyToManyField(related_name='role_permitted_petugas', to='master_petugas.rolemitra', verbose_name='Role Petugas'),
        ),
    ]
