# Generated by Django 5.0 on 2024-12-10 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_penilaian', '0014_remove_kegiatanpenilaianmodel_nama_kegiatan_and_more'),
        ('master_petugas', '0019_remove_alokasipetugas_honorperolehan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatanpenilaianmodel',
            name='kegiatan_survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='penilaian_survei', to='master_petugas.subkegiatansurvei', verbose_name='Kegiatan Survei'),
        ),
    ]
