# Generated by Django 5.0 on 2024-12-10 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_penilaian', '0015_alter_kegiatanpenilaianmodel_kegiatan_survey'),
        ('master_survey', '0006_remove_surveymodel_status_subkegiatansurvei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatanpenilaianmodel',
            name='kegiatan_survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='penilaian_survei', to='master_survey.subkegiatansurvei', verbose_name='Kegiatan Survei'),
        ),
    ]
