# Generated by Django 5.0 on 2024-12-11 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_penilaian', '0016_alter_kegiatanpenilaianmodel_kegiatan_survey'),
        ('master_petugas', '0021_alter_alokasipetugas_sub_kegiatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masternilaipetugas',
            name='penilai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilai', to='master_petugas.alokasipetugas'),
        ),
    ]
